<a href="https://colab.research.google.com/github/SamyakPatil19/NLP_PROJECT/blob/main/NLP_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])

In [5]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [7]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [8]:
unique_emotions=df['emotion'].unique()
emotion_number ={}
i =0
for emotion in unique_emotions:
    emotion_number[emotion]=i
    i+=1

df['emotion'] = df['emotion'].map(emotion_number)

In [9]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

CONVERTING TEXT INTO LOWERCASE

In [10]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [11]:
df['text']=df['text'].apply(lambda  x : x.lower())

REMOVING PUNCTUATION

In [12]:
import string

In [13]:
def removing_punch(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [14]:
df['text']=df['text'].apply(removing_punch)

REMOVING NUMBERS

In [15]:
def remove_number(text):
  new=''
  for i in text:
    if not i.isdigit():
        new=new+i
  return new

df['text']=df['text'].apply(remove_number)

REMOVE URL AND LINK

In [16]:
import re
def remove_urls(text):
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)
df['text'] = df['text'].apply(remove_urls)

REMOVE HTML TAGS

In [17]:

def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
df['text'] = df['text'].apply(remove_html_tags)

REMOVE EMOJIES AND CHARASCTRER

In [18]:
def remove_emojis(text):
  new=''
  for i in text:
    if i.isascii(): # This condition means: if the character IS ASCII, then add it to 'new'.
        new=new+i
  return new

df['text']=df['text'].apply(remove_emojis)

In [19]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

REMOVE STOPWORDS

In [20]:
import nltk

In [21]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [22]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [23]:
stop_words = set(stopwords.words('english'))

In [24]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [25]:
len(stop_words)

198

In [26]:

def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [27]:
df['text'] = df['text'].apply(remove)

In [28]:


df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [29]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.768125

In [32]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [33]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

pred_tfidf = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test,pred_tfidf))

0.6609375

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
LogisticRegression_model = LogisticRegression()
LogisticRegression_model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [37]:
log_pred = LogisticRegression_model.predict(X_test_tfidf)

In [38]:
print(accuracy_score(y_test,log_pred))

0.8628125